### PR TITLE
Better support pkg_resources to freeze app

### PR DESCRIPTION
**Pull request by marcelotduarte**
This pull requests superseds the previous #62

### CODE REVIEW

**Comment by amol-** [comment]
Is there a way to test this for real or should we rely on resource_filename monkeypatching to trigger the situation? I'm willing to merge this patch as it shouldn't touch the normal flow, but I cannot merge it unless it's provided with a test.

**Comment by marcelotduarte** [comment]
I had a real app running in both modes: fronzen and called via gearbox. I had a fullstack test at https://github.com/marcelotduarte/test-tg2-freeze

**Comment by amol-** [comment]
Yep, but to merge the changes I need to add a test unit that bring coverage to 100% to avoid regressions on that part. Otherwise I can't merge code that without checking it continues to work in the future.

I think we should be able to provide a test unit by monkeypatching `resource_filename` to throw a `NotImplementedError` as `resource_stream` should work also for normal files.

Also I suggest to switch to a context manager for closing the stream returned by `resource_stream` and the created temporary file.

Last it's probably not really efficient to recreate the file each and every single time, it should probably check if it already exists and keep it. If you are afraid the content of the file is wrong that can be avoided by using a randomly generated `__temp_dir` instead of relying on `executable` name, including the current timestamp or an uuid should be enough and as it is saved inside the `DottedFileNameFinder` it should be generated only once. It can even be generated by `__init__` so that we take for granted it's always available.

**Comment by marcelotduarte** [comment]
As a I have time, I will add tests...
I think not cause regressions, why, actually, I'm just dealing with one exception.

Also, for context manager:
with resource_stream(package, basename) as rd, open(result, 'wb') as fp:
    fp.write(rd.read())
Does not break compatibility with olders versions of python?

And, for "it's probably not really efficient to recreate the file each and every single time":
The result is go to cache like any normal filename, in : return self.__cache[template_name] above, then it is ready only when the "program" is started.

I had thought of using uuid, and as you suggest, I will use.

**Comment by amol-** [comment]
My concern on regressions is that we must ensure it will work on the future and detect before shipping in case it breaks. TurboGears2 has constraint of 100% code coverage, so unless it's tested we cannot merge new code.

Regarding ``with`` that isn't a problem, TurboGears2 only supports Python 2.6+

I'll merge this as soon as a test is available, so that we can release this in 2.3.9 / 2.4

**Comment by amol-** [comment]
https://github.com/TurboGears/tg2/commit/5ded9fb26d9b33396cbf4c59cca321d7e67070f3 also adapts it for generic zip support and adds test

**Pull request merged**
