### PR TITLE
Pagination PostgreSQL performance optimization

### PR DESCRIPTION
**Pull request by barjomet**
PostgreSQL is popular nowadays and known for it's [poor counting performance](https://wiki.postgresql.org/wiki/Slow_Counting).
What I usually do when using tg.support.paginate is monkeypatching of `_SQLAlchemyQueryWrapper.__len__` method.
Usually it saves 25%-75% of query execution time, on large tables it's hundreds of milliseconds or even seconds.
What does it do:
reduces query
```
SELECT count(*) AS count_1 
FROM (SELECT tablename.col_1 AS tablename_col_1, tablename.col_2 AS tablename_col_2, …, tablename.col_n AS tablename_col_n
FROM tablename ORDER BY tablename.col_1 DESC) AS anon_1
```
to 
```
SELECT count(*) AS count_1 
FROM tablename
```
so it drops ORDER BY and select columns, making index only scans possible.

Another possible pagination optimization is to reduce LIMIT-OFFSET overhead. Pre-selecting with limit-offset in subquery make use of `index only scan` through whole table, instead of `index scan` which is much slower. For my dev project tables with 100K rows this makes fetching paginated data for page 4000 twice faster.
I can make additional tests if needed. 

UPD: Not sure how it shoutd be covered with tests with current test environment. May it be better to create separate extension for such improvements?

Thanks

### CODE REVIEW

**Comment by amol-** [comment]
We need to cover this somehow at least to ensure it continues to work, what concerns me is not that the performance improvement might get lost, but that it might stop working at all.

Does the generated SQL work on sqlite too? We don't care if performance are better or worse in the test, but if the resulting query can work on sqlite we should have a test that runs it to prevent future regressions.

Also, instead of adding complexity to `_SQLAlchemyQueryWrapper` we probably want to have an additional `_PGSQLAlchemyQueryWrapper` and select the right one in `_wrap_collection`

**Comment by barjomet** [comment]
Oh yes, I just didn't think this way. It uses no PostgreSQL specific SQL, and should not only work on MySQL an SQLite but also optimize them too, maybe not so dramatically. I'll check it, I have a doubt that my limit-offset optimization may decrease performance on tables with big number of columns.

I think there will be _PerformantSQLAlchemyQueryWrapper common for all sqlalchemy backends and original _SQLAlchemyQueryWrapper as fallback variant. Please, correct me if I'm wrong.

Thus there's no need in dbsession engine driver check and no issues with test coverage, we can even compare wrappers performance in tests.

**Comment by barjomet** [comment]
Played [here](https://github.com/barjomet/tgtest) with this optimization and PostgreSQL, MySQL, SQLite with production-flavor db's setup. 
Conclusion — it's poor performance improvement, not consistent gains, in some cases makes queries slower. 
I think my better results are specific for dataset and database configuration combination.
The best way to apply this optimizations is mokeypatch.
My apologize for taking your time.

**Comment by amol-** [comment]
Thanks in any case for submitting the patch for review and spending time checking the performance improvement. I appreciated your contribution.

**Comment by barjomet** [comment]
Thank you, I like turbogears2. Most of my current work projects are build with it, so I gonna contribute a lot more.
Just wondering what kind of features are requested and welcome by community, may be I have something to share.

**Pull request closed without merging**
